#!/usr/bin/env bash
# env-lib.sh — helpers shared by env.sh (read/validate) and env-write.sh
# (init/propagate). Sourced, never executed; the caller owns `set -euo pipefail`
# and must have set $repo, $ENV_FILE and $EXAMPLE_FILE first.
# env-lib.sh——env.sh 与 env-write.sh 共用的工具函数；仅被 source，不可直接执行。
#
# Splitting these out is what the ~350-line modular-file budget was waiting
# for: see docs/issues/2026-07-29-envsh-line-budget.md.

# ── the component map · 组件映射 ─────────────────────────────────────────────
#
# `-` means "known component, but it consumes no .env file". The Go binary
# reads process env via os.Getenv and has no dotenv dependency, so generating a
# server/.env would produce a file nothing loads — false confidence, which is
# worse than no file. Keep the arm rather than falling through to "unknown", so
# `propagate server` explains itself instead of looking like a typo.
# `-` 表示“已知组件但不消费 .env 文件”：Go 端只读进程环境变量。
COMPONENTS="server client"
component_dir() {
  case "$1" in
    # Neither consumes a generated .env: Go reads os.Getenv; Flutter
    # reads --dart-define=API_BASE. Keep the arms so `propagate server`
    # and `dev.sh -C client` are not treated as typos.
    server|client) echo - ;;
    *)      echo "" ;;
  esac
}

# ── provenance stamps · 溯源标记 ─────────────────────────────────────────────
#
# A comment saying "do not edit" is not a mechanism; a checksum is. Two are
# needed, and the first alone is not enough:
#   root-env-sha — fingerprints the SOURCE, so a copy left behind by an edited
#                  root file is detected (drift).
#   body-sha     — fingerprints the COPY's own payload, so a copy hand-edited
#                  after generation is detected too (tampering). Without it a
#                  changed copy still reports "in sync", which is precisely the
#                  silent override the stamp exists to prevent.
GEN_MARK='# generated by scripts/env.sh propagate — DO NOT EDIT'
SUM_MARK='# root-env-sha:'
BODY_MARK='# body-sha:'

root_sum() {
  local s
  s="$(shasum -a 256 "$1" 2>/dev/null | cut -c1-16)" || s=""
  if [ -z "$s" ]; then
    echo "FAIL: cannot fingerprint $1 — is 'shasum' on PATH? (it is what detects a stale component copy)" >&2
    return 1
  fi
  printf '%s\n' "$s"
}
# The payload only: comments and blanks excluded, so the header is not part of
# its own hash. `grep -v` exits 1 when nothing matches (an empty payload is
# legitimate here), hence the `|| true` — the classic trap.
body_sum() {
  { grep -vE '^[[:space:]]*(#|$)' "$1" 2>/dev/null || true; } | shasum -a 256 | cut -c1-16
}

# ── skeleton reading · 读取骨架 ──────────────────────────────────────────────
#
# The skeletons ARE the variable list. env.sh used to carry a hardcoded
# KNOWN_NAMES, and it had already drifted — it knew GITHUB_TOKEN and
# unused names, which no skeleton declared. One list, derived.
# 骨架文件即变量清单；此前硬编码的清单已与骨架不一致，故改为派生。
skeleton_files() {
  local c d
  printf '%s\n' "$EXAMPLE_FILE"
  for c in $COMPONENTS; do
    d="$(component_dir "$c")"
    [ "$d" != - ] && [ -n "$d" ] || continue
    printf '%s\n' "$repo/$d/.env.example"
  done
}
# Every name any skeleton declares, commented or not, one per line.
skeleton_names() {
  local f
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    sed -nE 's/^#?[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "$f"
  done < <(skeleton_files) | sort -u
}

# ── loading · 读取 ───────────────────────────────────────────────────────────

# Emit `declare`/`unset` lines describing what $ENV_FILE — and ONLY $ENV_FILE —
# sets. Callers eval the result in their own scope.
#
# Two hazards this closes, both found by exercising it against a failing input:
#
#  1. The subshell inherits the caller's exported variables, and `declare -p`
#     cannot tell those from ones the file assigned. `check` therefore passed
#     on a zero-byte .env whenever the operator's shell happened to export
#     DATABASE_URL (direnv, CI secrets, an earlier `source .env`) — the gate
#     opening in exactly the direction it guards. So: clear every known name
#     first, and emit an explicit `unset` for each one the file does not set,
#     which clears the caller's ambient copy too. compose and
#     docker compose reads the file, not your shell; the file is the
#     authority here.
#  2. bash echoes the offending LINE when it cannot parse an assignment, and
#     that line contains the value. Redirect the subshell's stderr and report
#     the line NUMBER instead.
# 仅以文件为准（清除环境中的同名变量），并屏蔽 bash 的解析报错——其中含有值。
load_env() {
  local n rc errfile lines
  errfile="$(mktemp "${TMPDIR:-/tmp}/insideout-env.XXXXXX")"
  ( while IFS= read -r n; do unset "$n"; done < <(skeleton_names)
    set -a; . "$ENV_FILE" || exit 1; set +a
    while IFS= read -r n; do
      declare -p "$n" 2>/dev/null || printf 'unset %s\n' "$n"
    done < <(skeleton_names) ) 2>"$errfile"
  rc=$?
  if [ "$rc" -ne 0 ] || [ -s "$errfile" ]; then
    lines="$(sed -nE 's/.*: line ([0-9]+):.*/\1/p' "$errfile" | sort -un | tr '\n' ',' | sed 's/,$//')"
    rm -f "$errfile"
    echo "FAIL: cannot parse $ENV_FILE${lines:+ (line ${lines})} — quote any value containing a space, quote or \$, e.g. KEY='two words'." >&2
    echo "      (bash's own diagnostic is suppressed here: it would echo the value.)" >&2
    exit 1
  fi
  rm -f "$errfile"
}

# ── masking · 脱敏 ───────────────────────────────────────────────────────────

mask_secret() { # length only, never the value / 只显示长度
  if [ -n "$1" ]; then echo "set (${#1} chars)"; else echo "empty"; fi
}
# Show enough of a DSN to orient (which host?) and never a credential.
# Anchors on the LAST '@' (greedy) so an '@' inside a password is fully masked.
# Any shape we cannot confidently redact — a libpq keyword/value DSN
# (`host=… password=…`), or a URL carrying a credential query parameter — is
# masked whole rather than guessed at; both leaked verbatim before.
# 无法确信能安全脱敏的形式一律整体遮蔽，而非猜测。
redact_url() {
  local v="$1" low
  [ -n "$v" ] || { echo "empty"; return 0; }
  low="$(printf '%s' "$v" | tr '[:upper:]' '[:lower:]')"
  case "$low" in
    *password=*|*passfile=*|*sslpassword=*) mask_secret "$v"; return 0 ;;
  esac
  case "$v" in
    postgres://*|postgresql://*)
      printf '%s\n' "$v" | sed -E 's#(postgres(ql)?://).*@#\1***@#' ;;
    *) mask_secret "$v" ;;
  esac
}
url_password() { # extract (never print) the embedded password / 提取内嵌密码
  printf '%s\n' "$1" | sed -nE 's#^postgres(ql)?://[^:/@]+:(.*)@[^@/]*.*#\2#p'
}
# Render a value so `set -a; . .env` reads it back — mirrors env_catalog.quote.
quote_val() {
  case "$1" in
    "") : ;;
    *[!A-Za-z0-9_./:@%+,=~^-]*)
      case "$1" in
        *\'*) printf '"%s"' "$(printf '%s' "$1" | sed -e 's/[\\"$`]/\\&/g')"; return 0 ;;
        *)    printf "'%s'" "$1"; return 0 ;;
      esac ;;
  esac
  printf '%s' "$1"
}
# DATABASE_URL points at the bundled compose postgres (setup b)?
# POSTGRES_PORT is an advertised knob, so the mapped host port is not always
# 5442 — but only localhost forms are matched on it, or a remote DSN that
# happened to use the same port would raise a false alarm.
# 仅对 localhost 形式使用可配置端口，避免对远程 DSN 误报。
is_bundled_pg() {
  case "${DATABASE_URL:-}" in
    *@postgres:*|*@postgres/*|*:5442*) return 0 ;;
  esac
  if [ -n "${POSTGRES_PORT:-}" ]; then
    case "${DATABASE_URL:-}" in
      *@localhost:${POSTGRES_PORT}*|*@127.0.0.1:${POSTGRES_PORT}*) return 0 ;;
    esac
  fi
  return 1
}
# The same two markers scripts/env_catalog.py uses, so the checker and the
# catalog agree about what counts as "copied from the skeleton, never filled
# in". Deliberately NOT a generic '<' test — a bare-angle heuristic is how
# Piper's checker started rejecting legitimate values.
is_placeholder() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    *change_me*|*your-remote-host*) return 0 ;;
  esac
  return 1
}

# ── result markers · 结果标记 ────────────────────────────────────────────────
n_ok=0; n_warn=0; n_fail=0
ok()   { echo "ok: $1 — $2";   n_ok=$((n_ok+1)); }
warn() { echo "warn: $1 — $2"; n_warn=$((n_warn+1)); }
fail() { echo "FAIL: $1 — $2"; n_fail=$((n_fail+1)); }
info() { echo "info: $1 — $2"; }
