#!/usr/bin/env bash
# env-write.sh — the two env.sh verbs that CREATE files.
# env-write.sh——env.sh 中会写文件的两个子命令。
#
#   ./scripts/env.sh init                 # interactive: create .env, fill gaps
#   ./scripts/env.sh propagate [component] # regenerate component .env copies (none today)
#
# Sourced by env.sh, never run directly: it relies on that script's variables
# ($repo, $ENV_FILE, $EXAMPLE_FILE) and on env-lib.sh's helpers. Everything
# that only READS or VALIDATES stays in env.sh, so the split follows a real
# boundary rather than a line count.

# ── propagate · generate a component's .env from the root · 生成组件 .env ────
#
# Each component receives ONLY the keys its own committed .env.example
# declares, so a backend secret can never land in the frontend directory. The
# blast radius of a copy is bounded by a file that already had to exist.
# 每个组件仅接收其 .env.example 声明的键——后端密钥永远不会落到前端目录。
do_propagate() {
  local targets comp dir contract out sum key val n wrote refused
  [ -f "$ENV_FILE" ] || {
    echo "FAIL: no $ENV_FILE — run ./scripts/env.sh init" >&2; return 1; }
  # INSIDEOUT_ENV_FILE redirects the SOURCE but cannot redirect the
  # DESTINATION — the component directories belong to this checkout. Writing a
  # scratch file's values into a real component .env is exactly the accident a
  # testing knob must not cause, so refuse rather than half-honour it.
  # 测试用的环境变量只能改来源、改不了目标，故直接拒绝而非部分生效。
  if [ "$ENV_FILE" != "$repo/.env" ]; then
    echo "FAIL: propagate always writes into $repo, so it will not read from a redirected" >&2
    echo "      INSIDEOUT_ENV_FILE ($ENV_FILE) — that would write scratch values into the real component copies." >&2
    return 2
  fi
  targets="${*:-$COMPONENTS}"
  sum="$(root_sum "$ENV_FILE")"
  wrote=0; refused=0
  for comp in $targets; do
    dir="$(component_dir "$comp")"
    if [ -z "$dir" ]; then
      echo "FAIL: unknown component: $comp (expected one of: $COMPONENTS)" >&2
      return 2
    fi
    if [ "$dir" = - ]; then
      echo "skip: $comp — no dotenv file (process env / dart-define only)."
      echo "      Use ./scripts/dev.sh -C $comp <cmd>."
      continue
    fi
    contract="$repo/$dir/.env.example"
    out="$repo/$dir/.env"
    if [ ! -f "$contract" ]; then
      echo "skip: $comp — no $dir/.env.example to declare its contract"
      continue
    fi
    # Never write a secret where git could track it. The check MUST run inside
    # the owning directory: `git check-ignore "$dir/.env"` from the super-repo
    # consults the wrong .gitignore for a submodule and reports a properly
    # ignored file as trackable. 必须在目标目录内执行，否则会误判。
    if ! ( cd "$repo/$dir" && git check-ignore -q .env ) 2>/dev/null; then
      echo "refuse: $dir/.env is NOT ignored by git — add it to $dir/.gitignore first" >&2
      refused=1; continue
    fi
    # Refuse to clobber a file this tool did not write. The marker line is the
    # test; that refusal is also the deliberate-local-override escape hatch.
    if [ -f "$out" ] && ! grep -qF "$GEN_MARK" "$out"; then
      echo "refuse: $out exists and was NOT generated — it would be overwritten." >&2
      echo "        Move it aside first:  mv $dir/.env $dir/.env.manual.bak" >&2
      refused=1; continue
    fi
    # …and refuse to discard a human edit made to a generated file. The marker
    # alone cannot see this: the header survives an edit to the values below
    # it, so without the body checksum propagate silently overwrote the change.
    # 头部标记无法察觉正文被改动，故以正文校验和为准，避免静默覆盖人工修改。
    if [ -f "$out" ] && grep -qF "$BODY_MARK" "$out" \
       && [ "$(sed -n "s/^${BODY_MARK} //p" "$out" | head -1)" != "$(body_sum "$out")" ]; then
      echo "refuse: $out was EDITED after it was generated — regenerating would discard that change." >&2
      echo "        Discard it deliberately:  rm $dir/.env && ./scripts/env.sh propagate $comp" >&2
      echo "        Or keep it as a hand-written override: delete its '# generated by' header line." >&2
      refused=1; continue
    fi
    # Payload first, so its own checksum can be stamped into the header.
    : > "$out.body"
    n=0
    while IFS= read -r key; do
      [ -n "$key" ] || continue
      # A COMMENTED contract line (#KEY=) declares an OPTIONAL variable — still
      # part of the contract. Match it too, or an optional key the root
      # actually sets would never reach the component.
      grep -qE "^#?[[:space:]]*${key}=" "$contract" || continue
      # tail, not head: every reader of a dotenv resolves a duplicated key to
      # the LAST assignment — bash `set -a; . .env` executes them in order, and
      # so do compose and c12 — and appending an override at the bottom of the
      # file is ordinary practice. Taking the first would ship the component a
      # value the root itself does not use.
      # 取最后一次赋值，与 bash/compose/c12 的解析一致。
      val="$(sed -nE "s/^[[:space:]]*(export )?${key}=//p" "$ENV_FILE" | tail -1 || true)"
      printf '%s=%s\n' "$key" "$val" >> "$out.body"
      n=$((n+1))
    done < <(sed -nE 's/^[[:space:]]*(export )?([A-Za-z_][A-Za-z0-9_]*)=.*/\2/p' "$ENV_FILE" | awk '!seen[$0]++')
    { echo "$GEN_MARK"
      echo "$SUM_MARK $sum"
      echo "$BODY_MARK $(body_sum "$out.body")"
      echo "#"
      echo "# Source of truth is the repo root .env. Re-run \`./scripts/env.sh"
      echo "# propagate $comp\` after editing it; \`./scripts/env.sh check $comp\`"
      echo "# reports this file as stale if you forget — and as edited if you"
      echo "# change it here — and dev.sh refuses to launch $comp either way."
      echo "#"
      echo "# Scoped to $dir/.env.example — this component receives only the"
      echo "# keys it declares there."
      echo
      cat "$out.body"
    } > "$out.tmp"
    rm -f "$out.body"
    mv "$out.tmp" "$out"
    chmod 600 "$out"
    echo "wrote: $dir/.env — $n key(s) this component declares and the root sets"
    wrote=$((wrote+1))
  done
  echo "propagated to $wrote component(s) from $ENV_FILE (values never printed)"
  [ "$refused" -eq 0 ]
}

# ── init · interactive setup, tty only, never prints values · 交互式配置 ─────

changes=""
stage() { changes="${changes}$1=$2"$'\n'; }   # queue KEY=VALUE for write-back

# Write staged keys back: replace (uncommenting) the first '^#? *KEY=' line,
# else append. ponytail: awk + ENVIRON passes values literally — immune to
# sed's & / \ mangling. Same in-place semantics as env_catalog.set_var, so
# `init` and `edit` shape the file identically.
apply_changes() {
  [ -n "$changes" ] || return 0
  local tmp key val line
  tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
  cp "$ENV_FILE" "$tmp"
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    key="${line%%=*}"; val="${line#*=}"
    # Quoted so a value with a space or quote survives `set -a; . .env` — the
    # tool must never write a file its own reader rejects, and a space is legal
    # in a Postgres password. / 加引号，避免写出自身读不回的文件。
    val="$(quote_val "$val")"
    if grep -Eq "^#?[[:space:]]*${key}=" "$tmp"; then
      # LAST occurrence, matching bash/compose/c12: a duplicated key resolves
      # to the last assignment, so editing the first would write a value that
      # nothing then reads. / 取最后一次赋值，与各解析器一致。
      KEY_VALUE="$val" awk -v k="$key" '
        { line[NR] = $0; if ($0 ~ ("^#?[ \t]*" k "=")) last = NR }
        END { v = ENVIRON["KEY_VALUE"]
              for (i = 1; i <= NR; i++) print (i == last ? k "=" v : line[i]) }
      ' "$tmp" > "$tmp.new" && mv "$tmp.new" "$tmp"
    else
      if [ -n "$(tail -c 1 "$tmp")" ]; then printf '\n' >> "$tmp"; fi   # unfuse a missing final newline
      printf '%s=%s\n' "$key" "$val" >> "$tmp"
    fi
  done <<EOF
$changes
EOF
  chmod 600 "$tmp" && mv "$tmp" "$ENV_FILE"   # secrets file stays owner-only
}

do_init() {
  # Refuse without a tty — protects against pipe/cron clobbers / 非终端直接拒绝
  [ -t 0 ] || { echo "env.sh init needs an interactive terminal — edit $ENV_FILE by hand, or use ./scripts/env.sh edit" >&2; exit 1; }
  if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$EXAMPLE_FILE" ]; then
      cp "$EXAMPLE_FILE" "$ENV_FILE"; chmod 600 "$ENV_FILE"
      echo "created $ENV_FILE from $EXAMPLE_FILE"
    else
      echo "FAIL: neither $ENV_FILE nor $EXAMPLE_FILE exists — nothing to initialize from" >&2
      exit 1
    fi
  fi
  local input choice gen typed tok base model yn pw which url_pw load_out
  load_out="$(load_env)"; eval "$load_out"

  # (a) DATABASE_URL — required / 必填
  echo ""
  echo "DATABASE_URL — required. Two setups:"
  echo "  (a) remote — any host; the URL's role must own that database"
  echo "  (b) bundled compose postgres — 'docker compose up -d postgres', host port 5442 from localhost"
  echo "current: $(redact_url "${DATABASE_URL:-}")"
  printf 'DATABASE_URL (enter keeps current): '
  IFS= read -r -s input; echo
  if [ -n "$input" ]; then
    case "$input" in
      postgres://*|postgresql://*) : ;;
      *) echo "warn: a DSN normally starts with postgres:// — keeping what you typed" ;;
    esac
    DATABASE_URL="$input"; stage DATABASE_URL "$input"
  fi
  if [ -z "${DATABASE_URL:-}" ]; then
    echo "warn: DATABASE_URL is empty — the server will not start until it is set"
  elif is_placeholder "${DATABASE_URL:-}"; then
    echo "warn: DATABASE_URL still contains a placeholder — fix it before running"
  fi
  if is_bundled_pg && command -v docker >/dev/null 2>&1; then
    printf 'Start the bundled postgres now (docker compose up -d postgres)? [y/N] '
    IFS= read -r yn
    case "$yn" in
      y*|Y*) (cd "$repo" && docker compose up -d postgres) || echo "warn: docker compose up failed — start it later" ;;
    esac
  fi
  # (b) INSIDEOUT_JWT_SECRET — required, min 32 chars / 必填，至少 32 字符
  echo ""
  echo "INSIDEOUT_JWT_SECRET — required, min 32 chars. current: $(mask_secret "${INSIDEOUT_JWT_SECRET:-}")"
  while :; do
    printf '[g]enerate / [t]ype / [enter] keep: '
    IFS= read -r choice
    case "$choice" in
      g|G)
        if command -v openssl >/dev/null 2>&1; then
          gen="$(openssl rand -hex 32)"
          INSIDEOUT_JWT_SECRET="$gen"; stage INSIDEOUT_JWT_SECRET "$gen"
          echo "generated — $(mask_secret "$gen")"; break
        fi
        echo "FAIL: openssl not found — install it, or choose [t] to type a secret" ;;
      t|T)
        printf 'secret: '
        IFS= read -r -s typed; echo
        if [ "${#typed}" -ge 32 ]; then
          INSIDEOUT_JWT_SECRET="$typed"; stage INSIDEOUT_JWT_SECRET "$typed"
          echo "kept — $(mask_secret "$typed")"; break
        fi
        echo "warn: ${#typed} chars is under 32 — try again" ;;
      "")
        if [ -z "${INSIDEOUT_JWT_SECRET:-}" ]; then
          echo "no current value — choose [g] or [t]"
        elif is_placeholder "$INSIDEOUT_JWT_SECRET"; then
          echo "current value is a placeholder — choose [g] or [t]"
        else
          echo "keeping — $(mask_secret "$INSIDEOUT_JWT_SECRET")"; break
        fi ;;
      *) echo "choose g, t, or press enter" ;;
    esac
  done
  # (c) AI provider — empty token = offline template-reply coach / 留空即离线模式
  echo ""
  echo "AI provider — [enter] offline template-reply coach / [p]rovide token"
  printf 'choice: '
  IFS= read -r choice
  case "$choice" in
    p|P)
      printf 'INSIDEOUT_LLM_API_KEY: '
      IFS= read -r -s tok; echo
      if [ -n "$tok" ]; then INSIDEOUT_LLM_API_KEY="$tok"; stage INSIDEOUT_LLM_API_KEY "$tok"; fi
      printf 'INSIDEOUT_LLM_BASE_URL [%s]: ' "${INSIDEOUT_LLM_BASE_URL:-https://api.anthropic.com/v1}"
      IFS= read -r base
      base="${base:-${INSIDEOUT_LLM_BASE_URL:-https://api.anthropic.com/v1}}"
      stage INSIDEOUT_LLM_BASE_URL "$base"
      printf 'INSIDEOUT_LLM_MODEL [%s]: ' "${INSIDEOUT_LLM_MODEL:-claude-sonnet-4-20250514}"
      IFS= read -r model
      model="${model:-${INSIDEOUT_LLM_MODEL:-claude-sonnet-4-20250514}}"
      stage INSIDEOUT_LLM_MODEL "$model"
      printf 'INSIDEOUT_LLM_SCHEMA [%s]: ' "${INSIDEOUT_LLM_SCHEMA:-messages}"
      IFS= read -r schema
      schema="${schema:-${INSIDEOUT_LLM_SCHEMA:-messages}}"
      stage INSIDEOUT_LLM_SCHEMA "$schema"
      echo "configured — token $(mask_secret "${INSIDEOUT_LLM_API_KEY:-}")" ;;
    *)
      # Only write an empty value if one was previously set; otherwise leave
      # the line commented so the file keeps the skeleton's shape.
      if [ -n "${INSIDEOUT_LLM_API_KEY:-}" ]; then stage INSIDEOUT_LLM_API_KEY ""; fi
      echo "offline mode — template-reply coach" ;;
  esac
  # (d) GITHUB_TOKEN — optional / 可选
  echo ""
  printf 'GITHUB_TOKEN (optional, enter skips): '
  IFS= read -r -s tok; echo
  if [ -n "$tok" ]; then GITHUB_TOKEN="$tok"; stage GITHUB_TOKEN "$tok"; echo "saved — $(mask_secret "$tok")"
  else echo "skipped"; fi
  # (e) plain-http local serving → disable the Secure cookie / 纯 HTTP 本地开发
  echo ""
  printf 'Serving the app over plain http locally? [y/N] '
  IFS= read -r yn
  case "$yn" in
    y*|Y*) stage INSIDEOUT_COOKIE_SECURE 0
           echo "INSIDEOUT_COOKIE_SECURE=0 — Secure cookie disabled" ;;
    *) echo "keeping default (Secure cookie on)" ;;
  esac
  # (f) POSTGRES_APP_PASSWORD — bundled-postgres setup (b) only / 仅用法 (b)
  if is_bundled_pg; then
    echo ""
    echo "Bundled postgres detected — POSTGRES_APP_PASSWORD must match the password in DATABASE_URL."
    url_pw="$(url_password "$DATABASE_URL")"
    while :; do
      printf 'POSTGRES_APP_PASSWORD: '
      IFS= read -r -s pw; echo
      if [ -n "$url_pw" ] && [ "$pw" != "$url_pw" ]; then
        echo "warn: MISMATCH with the password embedded in DATABASE_URL"
        printf '[r]ewrite the URL password to match / [e]nter a different password: '
        IFS= read -r which
        case "$which" in
          r|R) # rewrite the URL password via awk+ENVIRON — a literal splice,
               # immune to sed-hostile & / \ # characters / 字面改写 URL 密码
            DATABASE_URL="$(URL_NEW_PW="$pw" DATABASE_URL="$DATABASE_URL" awk 'BEGIN {
              u = ENVIRON["DATABASE_URL"]; p = ENVIRON["URL_NEW_PW"]; out = u
              if (match(u, /^postgres(ql)?:\/\/[^:\/@]+:/)) {
                t = substr(u, RLENGTH + 1)
                for (i = length(t); i > 0; i--) if (substr(t, i, 1) == "@") break   # last @ bounds the password
                if (i > 0) out = substr(u, 1, RLENGTH) p substr(t, i)
              } print out }')"
            stage DATABASE_URL "$DATABASE_URL"; break ;;
          *) continue ;;
        esac
      fi
      break
    done
    stage POSTGRES_APP_PASSWORD "$pw"
    echo "saved — $(mask_secret "$pw")"
  fi
  apply_changes
  echo ""
  echo "saved $ENV_FILE — regenerating component copies:"
  # The stamp is now stale by construction (the root file just changed), and
  # dev.sh refuses to launch on a stale copy, so regenerate before validating.
  do_propagate || echo "warn: some components were not regenerated — see above"
  echo ""
  echo "validating:"
  do_check ""
}
